name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby (for xcodegen)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install xcodegen
        run: |
          gem install xcodegen

      - name: Generate Xcode project
        working-directory: iosApp/MobileApp
        run: xcodegen

      - name: Build .ipa with xcodebuild
        working-directory: iosApp/MobileApp
        run: |
          xcodebuild -project MobileApp.xcodeproj \
            -scheme MobileApp \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/MobileApp.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/MobileApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/export

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: MobileApp.ipa
          path: iosApp/MobileApp/build/export/*.ipa

