// Objective-C API for talking to github.com/pocchower/mobileapi Go package.
//   gobind -lang=objc github.com/pocchower/mobileapi
//
// File is generated by gobind. Do not edit.

#ifndef __Mobileapi_H__
#define __Mobileapi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Hello is a basic example function exported to iOS.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileapiHello(NSString* _Nullable name);

#endif
