
// Objective-C API for talking to the following Go packages
//
//	github.com/pocchower/mobileapi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MobileAPI_FRAMEWORK_H__
#define __MobileAPI_FRAMEWORK_H__

#include "Mobileapi.objc.h"
#include "Universe.objc.h"

#endif
