name: "Dockerfile build"
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
    - name: "Build Docker image"
      run: docker build .
