nano .github/workflows/export.yml
name: Export IPA

on:
  workflow_dispatch:

jobs:
  export-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby (required for xcodeproj tools)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Set up Xcode project
      run: |
        cd iosApp/MobileApp
        brew install xcodegen
        xcodegen generate

    - name: Build .xcarchive
      run: |
        xcodebuild archive \
          -scheme MobileApp \
          -project iosApp/MobileApp/MobileApp.xcodeproj \
          -configuration Release \
          -archivePath iosApp/MobileApp/build/MobileApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO

    - name: Export .ipa
      run: |
        xcodebuild -exportArchive \
          -archivePath iosApp/MobileApp/build/MobileApp.xcarchive \
          -exportPath iosApp/MobileApp/build/exported \
          -exportOptionsPlist iosApp/MobileApp/ExportOptions.plist

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: MobileApp.ipa
        path: iosApp/MobileApp/build/exported/*.ipa

